name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish templates manifest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: templates.yaml
        asset_name: templates.yaml
        tag: ${{ github.ref }}
        overwrite: true
    - name: Build and push the docker container
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: datamindedbe/cookiecutter
        tags: ${{ github.ref }}
