name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish templates manifest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: templates.yaml
        asset_name: templates.yaml
        tag: ${{ github.ref }}
        overwrite: true
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          datamindedbe/cookiecutter
        tags: |
          type=ref,event=tag
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push the docker container
      uses: docker/build-push-action@v5
      with:
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
