name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-templates:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          architecture: x64
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: install dev dependencies
        run: pip install -r dev-requirements.txt
      - name: flake8 and black
        run: |
          flake8 tests
          black --check tests
      - name: run tests
        run: pytest tests